[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "inform"
version = "0.1.0"
description = "Inference of Neural Functional Organization from Recruitment Matching"
authors = [
    {name = "Laura Toni"}
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "scikit-learn",
    "xgboost",
    "h5py",
    "joblib",
    "tqdm",
    "modAL",
    "pyswarms",
]

[tool.setuptools.packages.find]
where = ["."]
